
version: '3'

networks:
  ctso:
    external:
      name: ctso

services:
  ca_org1:
    image: hyperledger/fabric-ca:${CA_IMAGETAG}
    networks:
      ctso:
        aliases:
          - ca_org1
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
        constraints:
          - node.hostname == ${NODE1}
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca_org1.citysurvey.gov
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.citysurvey.gov-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/9803caa33867dccd92ec7bcc64c1ae5b47f88af39dbc938464eadabfe4d5306c_sk
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org1.citysurvey.gov-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/9803caa33867dccd92ec7bcc64c1ae5b47f88af39dbc938464eadabfe4d5306c_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/org1.citysurvey.gov/ca/:/etc/hyperledger/fabric-ca-server-config
