
version: '3'

networks:
  ctso:
    external:
      name: ctso

services:
  peer0_org1:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
        constraints:
          - node.hostname == ${NODE1}
    hostname: peer0.org1.citysurvey.gov
    image: hyperledger/fabric-peer:${IMAGETAG}
    networks:
      ctso:
        aliases:
          - peer0.org1.citysurvey.gov
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_ENDORSER_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_SKIPHANDSHAKE=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/peer0/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/peer0/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/peer0/tls/ca.crt
      - CORE_PEER_ID=peer0.org1.citysurvey.gov
      - CORE_PEER_ADDRESS=peer0.org1.citysurvey.gov:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.citysurvey.gov:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.citysurvey.gov:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      #
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=ctso
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0:5984

    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/org1.citysurvey.gov/peers/peer0.org1.citysurvey.gov/msp:/etc/hyperledger/peer0/msp
      - ./crypto-config/peerOrganizations/org1.citysurvey.gov/peers/peer0.org1.citysurvey.gov/tls:/etc/hyperledger/peer0/tls

  peer1_org1:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
        constraints:
          - node.hostname == ${NODE2}
    hostname: peer1.org1.citysurvey.gov
    image: hyperledger/fabric-peer:${IMAGETAG}
    networks:
      ctso:
        aliases:
          - peer1.org1.citysurvey.gov
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_ENDORSER_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_SKIPHANDSHAKE=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/peer1/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/peer1/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/peer1/tls/ca.crt
      - CORE_PEER_ID=peer1.org1.citysurvey.gov
      - CORE_PEER_ADDRESS=peer1.org1.citysurvey.gov:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.citysurvey.gov:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org1.citysurvey.gov:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      #
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=ctso
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1:5984

    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/org1.citysurvey.gov/peers/peer1.org1.citysurvey.gov/msp:/etc/hyperledger/peer1/msp
      - ./crypto-config/peerOrganizations/org1.citysurvey.gov/peers/peer1.org1.citysurvey.gov/tls:/etc/hyperledger/peer1/tls

  peer2_org1:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
        constraints:
          - node.hostname == ${NODE3}
    hostname: peer2.org1.citysurvey.gov
    image: hyperledger/fabric-peer:${IMAGETAG}
    networks:
      ctso:
        aliases:
          - peer2.org1.citysurvey.gov
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_ENDORSER_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_SKIPHANDSHAKE=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/peer2/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/peer2/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/peer2/tls/ca.crt
      - CORE_PEER_ID=peer2.org1.citysurvey.gov
      - CORE_PEER_ADDRESS=peer2.org1.citysurvey.gov:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.citysurvey.gov:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer2.org1.citysurvey.gov:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      #
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=ctso
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb2:5984

    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/org1.citysurvey.gov/peers/peer2.org1.citysurvey.gov/msp:/etc/hyperledger/peer2/msp
      - ./crypto-config/peerOrganizations/org1.citysurvey.gov/peers/peer2.org1.citysurvey.gov/tls:/etc/hyperledger/peer2/tls

  peer3_org1:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
        constraints:
          - node.hostname == ${NODE4}
    hostname: peer3.org1.citysurvey.gov
    image: hyperledger/fabric-peer:${IMAGETAG}
    networks:
      ctso:
        aliases:
          - peer3.org1.citysurvey.gov
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_ENDORSER_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_SKIPHANDSHAKE=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/peer3/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/peer3/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/peer3/tls/ca.crt
      - CORE_PEER_ID=peer3.org1.citysurvey.gov
      - CORE_PEER_ADDRESS=peer3.org1.citysurvey.gov:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.citysurvey.gov:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer3.org1.citysurvey.gov:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      #
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=ctso
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb3:5984

    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/org1.citysurvey.gov/peers/peer3.org1.citysurvey.gov/msp:/etc/hyperledger/peer3/msp
      - ./crypto-config/peerOrganizations/org1.citysurvey.gov/peers/peer3.org1.citysurvey.gov/tls:/etc/hyperledger/peer3/tls
