
version: '3'

networks:
  ctso:
    external:
      name: ctso

services:
  couchdb0:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
        constraints:
          - node.hostname == ${NODE1}
    hostname: couchdb0
    image: hyperledger/fabric-couchdb:${TP_IMAGETAG}
    networks:
      - ctso

  couchdb1:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
        constraints:
          - node.hostname == ${NODE2}
    hostname: couchdb1
    image: hyperledger/fabric-couchdb:${TP_IMAGETAG}
    networks:
      - ctso

  couchdb2:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
        constraints:
          - node.hostname == ${NODE3}
    hostname: couchdb2
    image: hyperledger/fabric-couchdb:${TP_IMAGETAG}
    networks:
      - ctso

  couchdb3:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
        constraints:
          - node.hostname == ${NODE4}
    hostname: couchdb3
    image: hyperledger/fabric-couchdb:${TP_IMAGETAG}
    networks:
      - ctso
