
version: '3'

networks:
  ctso:
    external:
      name: ctso

services:
  ca_org1:
    image: hyperledger/fabric-ca:${CA_IMAGETAG}
    networks:
      ctso:
        aliases:
          - ca_org1
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
        constraints:
          - node.hostname == ${NODE1}
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca_org1.citysurvey.gov
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.citysurvey.gov-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/9803caa33867dccd92ec7bcc64c1ae5b47f88af39dbc938464eadabfe4d5306c_sk
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org1.citysurvey.gov-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/9803caa33867dccd92ec7bcc64c1ae5b47f88af39dbc938464eadabfe4d5306c_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/org1.citysurvey.gov/ca/:/etc/hyperledger/fabric-ca-server-config

  couchdb0:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
        constraints:
          - node.hostname == ${NODE1}
    hostname: couchdb0
    image: hyperledger/fabric-couchdb:${TP_IMAGETAG}
    networks:
      - ctso

  couchdb1:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
        constraints:
          - node.hostname == ${NODE2}
    hostname: couchdb1
    image: hyperledger/fabric-couchdb:${TP_IMAGETAG}
    networks:
      - ctso

  couchdb2:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
        constraints:
          - node.hostname == ${NODE3}
    hostname: couchdb2
    image: hyperledger/fabric-couchdb:${TP_IMAGETAG}
    networks:
      - ctso

  couchdb3:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
        constraints:
          - node.hostname == ${NODE4}
    hostname: couchdb3
    image: hyperledger/fabric-couchdb:${TP_IMAGETAG}
    networks:
      - ctso

  peer0_org1:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
        constraints:
          - node.hostname == ${NODE1}
    hostname: peer0.org1.citysurvey.gov
    image: hyperledger/fabric-peer:${IMAGETAG}
    networks:
      ctso:
        aliases:
          - peer0.org1.citysurvey.gov
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_ENDORSER_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_SKIPHANDSHAKE=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/peer0/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/peer0/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/peer0/tls/ca.crt
      - CORE_PEER_ID=peer0.org1.citysurvey.gov
      - CORE_PEER_ADDRESS=peer0.org1.citysurvey.gov:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.citysurvey.gov:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.citysurvey.gov:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      #
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=ctso
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0:5984

    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/org1.citysurvey.gov/peers/peer0.org1.citysurvey.gov/msp:/etc/hyperledger/peer0/msp
      - ./crypto-config/peerOrganizations/org1.citysurvey.gov/peers/peer0.org1.citysurvey.gov/tls:/etc/hyperledger/peer0/tls
