
version: '3'

networks:
  ctso:
    external:
      name: ctso

services:
  ca_org1:
    image: hyperledger/fabric-ca:${CA_IMAGETAG}
    hostname: ca.org1.citysurvey.gov
    networks:
      ctso:
        aliases:
          - ca_org1
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
        constraints:
          - node.hostname == ${NODE1}
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca_org1.citysurvey.gov
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.citysurvey.gov-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/ad07f5125260c8131d016a2881d414520af77cb7bde5d931918cc1c45c3cce8a_sk
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.citysurvey.gov-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/ad07f5125260c8131d016a2881d414520af77cb7bde5d931918cc1c45c3cce8a_sk
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org1.citysurvey.gov-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/ad07f5125260c8131d016a2881d414520af77cb7bde5d931918cc1c45c3cce8a_sk -b admin:adminpw -d'
    ports:
      - 7054:7054
    volumes:
      - ./crypto-config/peerOrganizations/org1.citysurvey.gov/ca/:/etc/hyperledger/fabric-ca-server-config

  ca_org2:
    image: hyperledger/fabric-ca:${CA_IMAGETAG}
    hostname: ca.org2.citysurvey.gov
    networks:
      ctso:
        aliases:
          - ca_org2
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
        constraints:
          - node.hostname == ${NODE1}
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca_org2.citysurvey.gov
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org2.citysurvey.gov-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/5fb8482a258dd3d8eea9e0ca0c73f4d1298d57fd251d072d50523f139e0e0a13_sk
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org2.citysurvey.gov-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/5fb8482a258dd3d8eea9e0ca0c73f4d1298d57fd251d072d50523f139e0e0a13_sk
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org2.citysurvey.gov-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/5fb8482a258dd3d8eea9e0ca0c73f4d1298d57fd251d072d50523f139e0e0a13_sk -b admin:adminpw -d'
    ports:
      - 8054:7054
    volumes:
      - ./crypto-config/peerOrganizations/org2.citysurvey.gov/ca/:/etc/hyperledger/fabric-ca-server-config
