version: '3'

networks:
  ctso:
    external:
      name: ctso

services:
  kafka0:
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
        constraints:
          - node.hostname == ${NODE1}
    hostname: kafka0.citysurvey.gov
    image: hyperledger/fabric-kafka:${TP_IMAGETAG}
    networks:
      ctso:
        aliases:
          - kafka0.citysurvey.gov
    environment:
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=ctso
      - KAFKA_MESSAGE_MAX_BYTES=94371840          # 90 * 1024 * 1024 B
      - KAFKA_REPLICA_FETCH_MAX_BYTES=73400320    # 70 * 1024 * 1024 B
      - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
      - KAFKA_MIN_INSYNC_REPLICAS=2
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper0:2181,zookeeper1:2181,zookeeper2:2181
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS=12000000
      - KAFKA_ZOOKEEPER_SESSION_TIMEOUT_MS=12000000
    ports:
      - 9092:9092
      - 9093:9093

  kafka1:
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
        constraints:
          - node.hostname == ${NODE2}
    hostname: kafka1.citysurvey.gov
    image: hyperledger/fabric-kafka:${TP_IMAGETAG}
    networks:
      ctso:
        aliases:
          - kafka1.citysurvey.gov
    environment:
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=ctso
      - KAFKA_MESSAGE_MAX_BYTES=94371840          # 90 * 1024 * 1024 B
      - KAFKA_REPLICA_FETCH_MAX_BYTES=73400320    # 70 * 1024 * 1024 B
      - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
      - KAFKA_MIN_INSYNC_REPLICAS=2
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper0:2181,zookeeper1:2181,zookeeper2:2181
      - KAFKA_BROKER_ID=2
      - KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS=12000000
      - KAFKA_ZOOKEEPER_SESSION_TIMEOUT_MS=12000000
    ports:
      - 10092:9092
      - 10093:9093

  kafka2:
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
        constraints:
          - node.hostname == ${NODE3}
    hostname: kafka2.citysurvey.gov
    image: hyperledger/fabric-kafka:${TP_IMAGETAG}
    networks:
      ctso:
        aliases:
          - kafka2.citysurvey.gov
    environment:
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=ctso
      - KAFKA_MESSAGE_MAX_BYTES=94371840          # 90 * 1024 * 1024 B
      - KAFKA_REPLICA_FETCH_MAX_BYTES=73400320    # 70 * 1024 * 1024 B
      - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
      - KAFKA_MIN_INSYNC_REPLICAS=2
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper0:2181,zookeeper1:2181,zookeeper2:2181
      - KAFKA_BROKER_ID=3
      - KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS=12000000
      - KAFKA_ZOOKEEPER_SESSION_TIMEOUT_MS=12000000
    ports:
      - 11092:9092
      - 11093:9093

  kafka3:
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
        constraints:
          - node.hostname == ${NODE4}
    hostname: kafka3.citysurvey.gov
    image: hyperledger/fabric-kafka:${TP_IMAGETAG}
    networks:
      ctso:
        aliases:
          - kafka3.citysurvey.gov
    environment:
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=ctso
      - KAFKA_MESSAGE_MAX_BYTES=94371840          # 90 * 1024 * 1024 B
      - KAFKA_REPLICA_FETCH_MAX_BYTES=73400320    # 70 * 1024 * 1024 B
      - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
      - KAFKA_MIN_INSYNC_REPLICAS=2
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper0:2181,zookeeper1:2181,zookeeper2:2181
      - KAFKA_BROKER_ID=4
      - KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS=12000000
      - KAFKA_ZOOKEEPER_SESSION_TIMEOUT_MS=12000000
    ports:
      - 12092:9092
      - 12093:9093
