
version: '3'

networks:
  ctso:
    external:
      name: ctso

services:
  couchdb0:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
        constraints:
          - node.hostname == ${NODE1}
    hostname: couchdb0
    image: hyperledger/fabric-couchdb:${TP_IMAGETAG}
    ports:
      - 5984:5984
    networks:
      - ctso

  couchdb1:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
        constraints:
          - node.hostname == ${NODE2}
    hostname: couchdb1
    image: hyperledger/fabric-couchdb:${TP_IMAGETAG}
    ports:
      - 6984:5984
    networks:
      - ctso

  couchdb2:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
        constraints:
          - node.hostname == ${NODE3}
    hostname: couchdb2
    image: hyperledger/fabric-couchdb:${TP_IMAGETAG}
    ports:
      - 7984:5984
    networks:
      - ctso

  couchdb3:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
        constraints:
          - node.hostname == ${NODE4}
    hostname: couchdb3
    image: hyperledger/fabric-couchdb:${TP_IMAGETAG}
    ports:
      - 8984:5984
    networks:
      - ctso

  couchdb4:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
        constraints:
          - node.hostname == ${NODE1}
    hostname: couchdb4
    image: hyperledger/fabric-couchdb:${TP_IMAGETAG}
    ports:
      - 9984:5984
    networks:
      - ctso

  couchdb5:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
        constraints:
          - node.hostname == ${NODE2}
    hostname: couchdb5
    image: hyperledger/fabric-couchdb:${TP_IMAGETAG}
    ports:
      - 10984:5984
    networks:
      - ctso

  couchdb6:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
        constraints:
          - node.hostname == ${NODE3}
    hostname: couchdb6
    image: hyperledger/fabric-couchdb:${TP_IMAGETAG}
    ports:
      - 11984:5984
    networks:
      - ctso

  couchdb7:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
        constraints:
          - node.hostname == ${NODE4}
    hostname: couchdb7
    image: hyperledger/fabric-couchdb:${TP_IMAGETAG}
    ports:
      - 12984:5984
    networks:
      - ctso
