
version: '3'

networks:
  ctso:
    external:
      name: ctso

services:
  ca_org1:
    image: hyperledger/fabric-ca:${CA_IMAGETAG}
    hostname: ca.org1.citysurvey.gov
    networks:
      ctso:
        aliases:
          - ca_org1
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
        constraints:
          - node.hostname == ${NODE1}
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca_org1.citysurvey.gov
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.citysurvey.gov-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/bc1e5b8bf753a4f8d832278ec280db97584c0f0f59f607c9ec119c6b26dabdd5_sk
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.citysurvey.gov-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/bc1e5b8bf753a4f8d832278ec280db97584c0f0f59f607c9ec119c6b26dabdd5_sk
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org1.citysurvey.gov-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/bc1e5b8bf753a4f8d832278ec280db97584c0f0f59f607c9ec119c6b26dabdd5_sk -b admin:adminpw -d'
    ports:
      - 7054:7054
    volumes:
      - ./crypto-config/peerOrganizations/org1.citysurvey.gov/ca/:/etc/hyperledger/fabric-ca-server-config

  ca_org2:
    image: hyperledger/fabric-ca:${CA_IMAGETAG}
    hostname: ca.org2.citysurvey.gov
    networks:
      ctso:
        aliases:
          - ca_org2
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
        constraints:
          - node.hostname == ${NODE1}
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca_org2.citysurvey.gov
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org2.citysurvey.gov-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/b7c9cf5154e22e2ae46ba9f1020658bacda9f0656e950304f4dc118b1a494eb0_sk
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org2.citysurvey.gov-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/b7c9cf5154e22e2ae46ba9f1020658bacda9f0656e950304f4dc118b1a494eb0_sk
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org2.citysurvey.gov-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/b7c9cf5154e22e2ae46ba9f1020658bacda9f0656e950304f4dc118b1a494eb0_sk -b admin:adminpw -d'
    ports:
      - 8054:7054
    volumes:
      - ./crypto-config/peerOrganizations/org2.citysurvey.gov/ca/:/etc/hyperledger/fabric-ca-server-config
