version: '3'

networks:
  ctso:
    external: true

services:
  ca_org1:
    hostname: ca.org1.citysurvey.gov
    image: hyperledger/fabric-ca:${IMAGETAG}
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca_org1.citysurvey.gov
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.citysurvey.gov-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/9803caa33867dccd92ec7bcc64c1ae5b47f88af39dbc938464eadabfe4d5306c_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/org1.citysurvey.gov/ca/:/etc/hyperledger/fabric-ca-server-config
    extra_hosts:
      - "ca.org1.citysurvey.gov:192.168.10.70"
    container_name: ca_org1
    networks:
      - ctso

  zookeeper0:
    image: hyperledger/fabric-zookeeper:${IMAGETAG}
    environment:
      - ZOO_SERVERS=server.1=zookeeper0:2888:3888 server.2=zookeeper1:2888:3888 server.3=zookeeper2:2888:3888
      - ZOO_MY_ID=1
    restart: always
    hostname: zookeeper0.citysurvey.gov
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
        constraints:
          - node.hostname == ${NODE1}

  kafka0:
    hostname: kafka0.citysurvey.gov
    image: hyperledger/fabric-kafka:${IMAGETAG}
    restart: always
    environment:
      - KAFKA_MESSAGE_MAX_BYTES=94371840          # 90 * 1024 * 1024 B
      - KAFKA_REPLICA_FETCH_MAX_BYTES=73400320    # 70 * 1024 * 1024 B
      - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
      - KAFKA_MIN_INSYNC_REPLICAS=2
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper0:2181,zookeeper1:2181,zookeeper2:2181
      - KAFKA_BROKER_ID=1
    ports:
      - 9092:9092
    depends_on:
      - zookeeper0
      # - zookeeper1
      # - zookeeper2
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
        constraints:
          - node.hostname == ${NODE1}

  orderer0:
    container_name: orderer0
    hostname: orderer0.citysurvey.gov
    image: hyperledger/fabric-orderer:${IMAGETAG}
    environment:
      - ORDERER_GENERAL_LOGLEVEL=info
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/orderer0/msp
      # Enable TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/etc/hyperledger/orderer0/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/etc/hyperledger/orderer0/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/etc/hyperledger/orderer0/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderer
    command: orderer
    ports:
      - 7050:7050
    depends_on:
      - kafka0
      # - kafka1
      # - kafka2
      # - kafka3
    volumes:
      - ./config/:/etc/hyperledger/configtx
      - ./crypto-config/ordererOrganizations/citysurvey.gov/orderers/orderer0.citysurvey.gov/msp:/etc/hyperledger/orderer0/msp
      - ./crypto-config/ordererOrganizations/citysurvey.gov/orderers/orderer0.citysurvey.gov/tls:/etc/hyperledger/orderer0/tls
        #      - orderer0.citysurvey.gov:/etc/hyperledger/production/orderer0

    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
        constraints:
          - node.hostname == ${NODE1} 

  peer0_org1:
    container_name: peer0_org1
    image: hyperledger/fabric-peer:${IMAGETAG}
    hostname: peer0.org1.citysurvey.gov
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock

      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=ctso
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_ENABLED=true

      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/peer0/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/peer0/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/peer0/tls/ca.crt
      - CORE_PEER_ADDRESS=peer0.org1.citysurvey.gov:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org1.citysurvey.gov:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.citysurvey.gov:7051

      - CORE_PEER_ID=peer0.org1.citysurvey.gov
      - CORE_LOGGING_PEER=info
      - CORE_CHAINCODE_LOGGING_LEVEL=info
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/peer0/msp
      # # the following setting starts chaincode containers on the same
      # # bridge network as the peers
      # # https://docs.docker.com/compose/networking/
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0:5984
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    # command: peer node start --peer-chaincodedev=true
    ports:
      - 7051:7051
      - 7053:7053
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/org1.citysurvey.gov/peers/peer0.org1.citysurvey.gov/msp:/etc/hyperledger/peer0/msp
      - ./crypto-config/peerOrganizations/org1.citysurvey.gov/peers/peer0.org1.citysurvey.gov/tls:/etc/hyperledger/peer0/tls
      - ./crypto-config/peerOrganizations/org1.citysurvey.gov/users:/etc/hyperledger/peer0/users
      - ./config:/etc/hyperledger/configtx
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
        constraints:
          - node.hostname == ${NODE1}
    # extra_hosts:
    #   - "orderer0.citysurvey.gov:${NODE1}"
    #   - "orderer1.citysurvey.gov:${NODE2}"
    #   - "orderer2.citysurvey.gov:${NODE3}"
    #   - "orderer3.citysurvey.gov:${NODE4}"
    #   - "peer1.org1.citysurvey.gov:${NODE2}"
    #   - "peer2.org1.citysurvey.gov:${NODE3}"
    #   - "peer3.org1.citysurvey.gov:${NODE4}"
    #   - "ca.org1.citysurvey.gov:${NODE1}"

    depends_on:
      - orderer0
      - couchdb0
    networks:
      - ctso

  couchdb0:
    container_name: couchdb0
    image: hyperledger/fabric-couchdb:${IMAGETAG}
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - 5984:5984
    networks:
      - ctso
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
        constraints:
          - node.hostname == ${NODE1}

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:${IMAGETAG}
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=info
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.org1.citysurvey.gov:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.citysurvey.gov/users/Admin@org1.citysurvey.gov/msp
      - CORE_CHAINCODE_KEEPALIVE=10
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
    networks:
        - ctso
    #depends_on:
    #  - orderer.citysurvey.gov
    #  - peer0.org1.citysurvey.gov
    #  - couchdb
